spring:
  application:
    name: myprojet

  jpa:
    open-in-view:false

  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create